USE InfinitMarketDB
SET IDENTITY_INSERT [dbo].[KategoriaProduktit] ON;
INSERT INTO [dbo].[KategoriaProduktit] ([KategoriaId], [LlojiKategoris], [PershkrimiKategoris], [isDeleted]) VALUES (2, 'Smartphone dhe Aksesore', '', 'false');
INSERT INTO [dbo].[KategoriaProduktit] ([KategoriaId], [LlojiKategoris], [PershkrimiKategoris], [isDeleted]) VALUES (3, 'Smart Watch dhe Aksesore', 'Ore te menqura te markave te ndryshme', 'false');
INSERT INTO [dbo].[KategoriaProduktit] ([KategoriaId], [LlojiKategoris], [PershkrimiKategoris], [isDeleted]) VALUES (4, 'Foto & Video', '', 'false');
INSERT INTO [dbo].[KategoriaProduktit] ([KategoriaId], [LlojiKategoris], [PershkrimiKategoris], [isDeleted]) VALUES (5, 'Audio dhe Kufje', '', 'false');
INSERT INTO [dbo].[KategoriaProduktit] ([KategoriaId], [LlojiKategoris], [PershkrimiKategoris], [isDeleted]) VALUES (6, 'All in One (AiO) PC', '', 'false');
INSERT INTO [dbo].[KategoriaProduktit] ([KategoriaId], [LlojiKategoris], [PershkrimiKategoris], [isDeleted]) VALUES (7, 'TV & Projektor', '', 'false');
INSERT INTO [dbo].[KategoriaProduktit] ([KategoriaId], [LlojiKategoris], [PershkrimiKategoris], [isDeleted]) VALUES (8, 'Maus & Aksesore', '', 'false');
INSERT INTO [dbo].[KategoriaProduktit] ([KategoriaId], [LlojiKategoris], [PershkrimiKategoris], [isDeleted]) VALUES (9, 'Lodra smart & Dron', '', 'false');
INSERT INTO [dbo].[KategoriaProduktit] ([KategoriaId], [LlojiKategoris], [PershkrimiKategoris], [isDeleted]) VALUES (10, 'Pjesë për kompjuter', 'Pjese te ndryshme per kompjuter, si: Ram, Procesor, GPU etj.', 'false');
INSERT INTO [dbo].[KategoriaProduktit] ([KategoriaId], [LlojiKategoris], [PershkrimiKategoris], [isDeleted]) VALUES (11, 'Wireless Charger', '', 'false');
INSERT INTO [dbo].[KategoriaProduktit] ([KategoriaId], [LlojiKategoris], [PershkrimiKategoris], [isDeleted]) VALUES (12, 'Tablet dhe Aksesore', '', 'false');
INSERT INTO [dbo].[KategoriaProduktit] ([KategoriaId], [LlojiKategoris], [PershkrimiKategoris], [isDeleted]) VALUES (13, 'Paisje Gaming', 'Fanella, Karrige dhe te tjera', 'false');
INSERT INTO [dbo].[KategoriaProduktit] ([KategoriaId], [LlojiKategoris], [PershkrimiKategoris], [isDeleted]) VALUES (14, 'Printer dhe Paisje per Printer', '', 'false');
INSERT INTO [dbo].[KategoriaProduktit] ([KategoriaId], [LlojiKategoris], [PershkrimiKategoris], [isDeleted]) VALUES (15, 'Kabllo te ndryshme & Adapter', '', 'false');
INSERT INTO [dbo].[KategoriaProduktit] ([KategoriaId], [LlojiKategoris], [PershkrimiKategoris], [isDeleted]) VALUES (16, 'Monitor dhe Aksesore', '', 'false');
INSERT INTO [dbo].[KategoriaProduktit] ([KategoriaId], [LlojiKategoris], [PershkrimiKategoris], [isDeleted]) VALUES (18, 'USB, SSD, HDD & Aksesore', '', 'false');
INSERT INTO [dbo].[KategoriaProduktit] ([KategoriaId], [LlojiKategoris], [PershkrimiKategoris], [isDeleted]) VALUES (19, 'Çanta Shpine', '', 'false');
INSERT INTO [dbo].[KategoriaProduktit] ([KategoriaId], [LlojiKategoris], [PershkrimiKategoris], [isDeleted]) VALUES (20, 'Tastiera dhe Aksesore', '', 'false');
INSERT INTO [dbo].[KategoriaProduktit] ([KategoriaId], [LlojiKategoris], [PershkrimiKategoris], [isDeleted]) VALUES (21, 'Karrige', '', 'false');
SET IDENTITY_INSERT [dbo].[KategoriaProduktit] OFF;
SET IDENTITY_INSERT [dbo].[KompanitePartnere] ON;
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (2, 'Amd', NULL, 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (3, 'Apple', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (4, 'JBL', NULL, 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (5, 'Lenovo', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (6, 'Logitech', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (7, 'MSI', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (8, 'Nvidia', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (9, 'Razer', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (10, 'Samsung', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (11, 'SteelSeries', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (12, 'Thermaltake', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (13, 'DJI', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (14, 'Overmax', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (15, 'G.Skill', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (16, 'Akasa', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (17, 'Corsair', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (18, 'WD - Western Digital', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (19, 'HP', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (20, 'Acer', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (21, 'ZOWIE - BenQ', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (22, 'Marvo', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (23, 'Arctic', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (24, 'Transcend', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (25, 'Dell', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (26, 'Instax', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (27, 'Canon', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (28, 'Sony', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (29, 'SENSE7', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (30, 'Preyon', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (31, 'Gjirafa50', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (32, 'Lenuo', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (33, 'Intel', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (34, 'AXAGON', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (35, 'FIXED', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (36, 'Kingston', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (37, 'Seasonic', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (38, 'Brother', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (39, 'UGREEN', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (40, 'HyperX', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (41, 'Gamebird', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (42, 'CZC.cz', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (43, 'Zotac', NULL, 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (44, 'SanDisk', '', 'false');
INSERT INTO [dbo].[KompanitePartnere] ([kompaniaID], [emriKompanis], [adresa], [isDeleted]) VALUES (45, 'YENKEE', '', 'false');
SET IDENTITY_INSERT [dbo].[KompanitePartnere] OFF;